#ifndef HONCH_CORE_STATUS_H
#define HONCH_CORE_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum honch_status {
    HONCH_STATUS_OK = 0,
    HONCH_STATUS_ERROR_INVALID_ARGUMENT = 1,
    HONCH_STATUS_ERROR_OUT_OF_MEMORY = 2,
    HONCH_STATUS_ERROR_IO = 3,
    HONCH_STATUS_ERROR_TRANSPORT = 4,
    HONCH_STATUS_ERROR_RATE_LIMITED = 5,
    HONCH_STATUS_ERROR_SERVER = 6,
    HONCH_STATUS_ERROR_REJECTED = 7,
    HONCH_STATUS_ERROR_NOT_INITIALIZED = 8,
    HONCH_STATUS_ERROR_ALREADY_INITIALIZED = 9,
    HONCH_STATUS_ERROR_QUEUE_FULL = 10,
    HONCH_STATUS_ERROR_TIMEOUT = 11,
    HONCH_STATUS_ERROR_INTERNAL = 12,
    HONCH_STATUS_ERROR_BUSY = 13,
    HONCH_STATUS_ERROR_NOT_SUPPORTED = 14
} honch_status_t;

#ifndef HONCH_CORE_NO_SHORT_STATUS_NAMES
#define HONCH_OK HONCH_STATUS_OK
#define HONCH_ERROR_INVALID_ARGUMENT HONCH_STATUS_ERROR_INVALID_ARGUMENT
#define HONCH_ERROR_OUT_OF_MEMORY HONCH_STATUS_ERROR_OUT_OF_MEMORY
#define HONCH_ERROR_IO HONCH_STATUS_ERROR_IO
#define HONCH_ERROR_TRANSPORT HONCH_STATUS_ERROR_TRANSPORT
#define HONCH_ERROR_RATE_LIMITED HONCH_STATUS_ERROR_RATE_LIMITED
#define HONCH_ERROR_SERVER HONCH_STATUS_ERROR_SERVER
#define HONCH_ERROR_REJECTED HONCH_STATUS_ERROR_REJECTED
#define HONCH_ERROR_NOT_INITIALIZED HONCH_STATUS_ERROR_NOT_INITIALIZED
#define HONCH_ERROR_ALREADY_INITIALIZED HONCH_STATUS_ERROR_ALREADY_INITIALIZED
#define HONCH_ERROR_QUEUE_FULL HONCH_STATUS_ERROR_QUEUE_FULL
#define HONCH_ERROR_TIMEOUT HONCH_STATUS_ERROR_TIMEOUT
#define HONCH_ERROR_INTERNAL HONCH_STATUS_ERROR_INTERNAL
#define HONCH_ERROR_BUSY HONCH_STATUS_ERROR_BUSY
#define HONCH_ERROR_NOT_SUPPORTED HONCH_STATUS_ERROR_NOT_SUPPORTED
#endif

#ifdef __cplusplus
}
#endif

#endif
