name: ESP-IDF Build

on:
  push:
    paths:
      - 'ports/esp-idf/**'
      - 'spec/**'
  pull_request:
    paths:
      - 'ports/esp-idf/**'
      - 'spec/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.3
    strategy:
      matrix:
        target: [esp32, esp32s3, esp32c3]
    steps:
      - uses: actions/checkout@v4

      - name: Build example for ${{ matrix.target }}
        working-directory: ports/esp-idf/example
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target ${{ matrix.target }}
          idf.py build
